### ISSUE TITLE
建议增加notificationDuration参数

### ISSUE THREAD

**Issue by jonahfang** [boyan01/overlay_support#1]
现在固定为2秒后自动消失，可以让用户自己规定。

**Comment by boyan01** [comment]
新暴露了 kNotificationDuration 这一全局变量，用作显示时常的控制。

https://github.com/boyan01/overlay_support/blob/f60a8de6063caa7e887ae1c11755467ec551de6f/lib/src/notification/overlay_notification.dart#L7
