### ISSUE TITLE
get callback from notification

### ISSUE THREAD

**Issue by MahdiPishguy** [boyan01/overlay_support#11]
you suppose i have textformfield on notification to get some information fro user, how can i get typed text from that?

**Comment by boyan01** [comment]
Do you means we could got some value  from `OverlayEntry`  when a notification dismissed ?

similar to `Route` ？
```
//get a result value after dialog dismissed
var result = await showDialog(xxxx);

//get a result value after page back
var result = await Navigator.push(context, xxxx);
```

**Comment by MahdiPishguy** [comment]
@boyan01 problem resolved
