### ISSUE TITLE
show opacity curtain under notifications

### ISSUE THREAD

**Issue by MahdiPishguy** [boyan01/overlay_support#13]
is any feature to show opacity curtain under notifications? like with dialogs

**Comment by boyan01** [comment]
I am confusing that If you want barrier background, why considering use Dialog instead ? 

And there be a way if you want barrier effect for Notification implement by this library.
`showOverlay` method might be you want, You can use this method to achieve any ui effect you want.

https://github.com/boyan01/overlay_support/blob/3eccccc653aabe6dc0315a65e98fcfa0f21bbd72/lib/src/overlay.dart#L50

**Comment by MahdiPishguy** [comment]
@boyan01 dialogs doesn't have any parameters for choose position of screen to show.

could you take a simple sample code for `showOverlay`?

**Comment by boyan01** [comment]
you could check the "example" project, `IosStyleToast` was pop by `showOverlay`
https://github.com/boyan01/overlay_support/blob/3eccccc653aabe6dc0315a65e98fcfa0f21bbd72/example/lib/main.dart#L117

**Comment by MahdiPishguy** [comment]
my mean is:

![screenshot1](https://user-images.githubusercontent.com/6617583/61028926-296bd000-a3cf-11e9-930c-f4c83eb1bb18.png)

**Comment by boyan01** [comment]
I add example just now.

https://github.com/boyan01/overlay_support/commit/5032ebf3c7347a326b5b75c3667abcb74854c98b

**Comment by boyan01** [comment]
but I think , custom a dialog could be a better solution.

**Comment by MahdiPishguy** [comment]
@boyan01 custom dialog doesn't have specify position to show view

**Comment by MahdiPishguy** [comment]
@boyan01 thanks to take me sample, that was what i want to have

**Comment by boyan01** [comment]
that's ok, all roads lead to Rome
