### ISSUE TITLE
implementing back pressed

### ISSUE THREAD

**Issue by MahdiPishguy** [boyan01/overlay_support#14]
is any solution for overlay support to implementing back pressed to close or dismiss notifications?

thanks

**Comment by boyan01** [comment]
https://stackoverflow.com/questions/49356664/how-to-override-the-back-button-in-flutter

**Comment by MahdiPishguy** [comment]
@boyan01 

are you sure we can implementing that with your introduced link?

https://stackoverflow.com/questions/57016822/flutter-override-back-button-for-multiple-willpops/57016943

**Comment by MahdiPishguy** [comment]
```dart
showOverlay((context, t) {
  // ignore: missing_return
  return Container(
    color: Color.lerp(Colors.transparent, Colors.black54, t),
    child: FractionalTranslation(
      translation: Offset.lerp(const Offset(0, -1), const Offset(0, 0), t),
      child: Column(
        children: <Widget>[
          DirectMessageNotification(
            message: "نظر خود را برای این پست تایپ کنید:",
            onReplay: () {
              OverlaySupportEntry.of(context).dismiss();
            },
            key: ModalKey(const Object()),
          ),
        ],
      ),
    ),
  );
}, duration: Duration.zero);



class DirectMessageNotification extends StatelessWidget {
  final VoidCallback onReplay;
  final String message;
  final bool enableBottomLayer;
  final bool enableHeaderLayer;

  const DirectMessageNotification({Key key, this.onReplay, @required this.message, this.enableBottomLayer, this.enableHeaderLayer}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    double notificationHeight = MediaQuery.of(context).size.height * 0.500;
    return SafeArea(
      child: WillPopScope(
        // ignore: missing_return
        onWillPop: () {
          if (onReplay != null) onReplay();
        },
        child: ,
      ),
    );
  }
}

```

**Comment by boyan01** [comment]
onWillPop function need a return value to determine whether intercept back event.

**Comment by MahdiPishguy** [comment]
@boyan01 i'm not sure to understand me, could you help me by code to know how can i do that? thanks

**Comment by boyan01** [comment]
sorry for late, it seems that `OverlaySupport` do not support this feature yet. because showOverlay is popup a `OverlayEntry` on screen, and this `OverlayEntry` do not belong to any `Route`, so `WillPopScope` is useless.

**Comment by boyan01** [comment]
also, I have no ideas how to intercept `BackEvent` on a `Widget` that not belong to any `Route`.

**Comment by boyan01** [comment]
the cost to implement back pressed for notification  is too expensive, it need override `Navigator` widget. so after consideration, I decided not to implement this feature.

**Comment by MahdiPishguy** [comment]
i think this library can help you to implementing that:

https://github.com/hey24sheep/backdrop_modal_route
