### ISSUE TITLE
set animate direction

### ISSUE THREAD

**Issue by MahdiPishguy** [boyan01/overlay_support#15]
in current implementation on library, animation control is top to bottom. how can i set direction to animate from bottom to top?

Thanks

**Comment by boyan01** [comment]
library expose a function named `showOverlay`

https://github.com/boyan01/overlay_support/blob/5032ebf3c7347a326b5b75c3667abcb74854c98b/lib/src/overlay.dart#L50

`showSimpleNotification`, `showNotification` and `toast` all used it to achieve the effect.  you can use this function to implement the custom behavior you want.

**Comment by MahdiPishguy** [comment]
@boyan01 
Thanks, i'm not sure to understand me whats animation controller on this class, whats in mind animations are `tween`

**Comment by boyan01** [comment]
you could use google `flutter tween` to get more info
