### ISSUE TITLE
Unhandled Exception when using showSimpleNotification

### ISSUE THREAD

**Issue by joaowd** [boyan01/overlay_support#2]
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: TimeoutException after 0:00:00.301000: Future not completed
null

**Comment by boyan01** [comment]
the assertion of hide method cause this exception to happen, It seems a bit redundant.
it just remove it in 861b9e6e5f51a6628979be94d39b2c5c77147f27 .

thanks for your feedback.
