### ISSUE TITLE
Is it possible to dismiss notification without using context?

### ISSUE THREAD

**Issue by callumclift** [boyan01/overlay_support#21]
Is it possible to dismiss notifications without using context? I can show the notification just fine without context but i'm unsure how to dismiss it without context, is this possible?

Here is my code but as you can see its requiring context which at the point of calling this i don't have:

`showSimpleNotification(
              Text("this is a message from simple notification"),
              background: Colors.green,
          autoDismiss: false,
          trailing: FlatButton(onPressed: (){
            
            OverlaySupportEntry.of(context).dismiss();
          }, child: Text('dismiss')))`

**Comment by boyan01** [comment]
it's impossible to dismiss notification without context, because we need a context to know which which notification you want to dismiss.

this this use case, you can wrap your `FlatButton` with a `WidgetBuilder` to obtain a context.
for example:
```dart
showSimpleNotification(
Text("this is a message from simple notification"),
trailing: Builder((context) {
  return FlatButton(
    onTap() {
      // you can get context here
    }    
  );
})
);
```

**Comment by ronniechew** [comment]
@boyan01 Thanks for this solution, using Builder to create a context works for me.
Perhaps this should go into the example page, I can see this can confuse some user as it's not that "simple" to dismiss a "
"showSimpleNotification" =)

Great plugin nonetheless!
