### ISSUE TITLE
Is it possible to dismiss any pending previous overlay before firing a new one?

### ISSUE THREAD

**Issue by bazurtovqhr** [boyan01/overlay_support#25]
Is it possible to dismiss any pending previous overlay before firing a new one?

Sometimes I fire a loading overlay and then the operation gets completed fast and shows a new overlay stating success, but the previous overlay (the one with the loading label) is still there behind the new one has shown up.

I want to be able to dismiss any pending or any other overlay is present in screen before showing the new one. is this possible? How can this be achieved based on a main context.

**Comment by boyan01** [comment]
https://github.com/boyan01/overlay_support/blob/346b90cf538b730f666c116de15239d7c0d7406f/lib/src/overlay.dart#L34


have you tried use the "key" parameter?

**Comment by bazurtovqhr** [comment]
Yes I managed to accomplish what i wanted by storing the keys of every fired overlay on a external data structure and then before firing a new overlay, check if there are some keys there to dismiss them.

I was interested in something like out of the box like a method such as dismissAll.
Thanks for the response

**Comment by boyan01** [comment]
Actually what I want point is that when you show a overlay with a key, this will cancel previous overlay with the same key.
