### ISSUE TITLE
Add duration parameter

### ISSUE THREAD

**Issue by hca2015** [boyan01/overlay_support#27]
Add Duration parameter to showSimpleNotification method, so that it can be a chosen value instead of a fixed duration.

**Comment by boyan01** [comment]
`kNotificationDuration` is not const , you can change this value if you want.

**Comment by hca2015** [comment]
Like this?

This will change the duration of all notifications, right?

`
//SimpleNotification
  static showMessageError(String prMessage) {
    kNotificationDuration = Duration(seconds: 5); // *******
    showSimpleNotification(Text(prMessage), background: Colors.red);
  }

  static showMessageSuccess(String prMessage) {
    showSimpleNotification(Text(prMessage), background: Colors.green);
  }

  static showMessageWarning(String prMessage) {
    showSimpleNotification(Text(prMessage), background: Colors.amber);
  }

  static showMessageSystem(String prMessage) {
    showSimpleNotification(Text(prMessage), background: Colors.cyan);
  }
`

**Comment by boyan01** [comment]
yes, this will change the duration of all notifications

**Comment by boyan01** [comment]
This issue is closed because there is no update
