### ISSUE TITLE
Fixed custom notification

### ISSUE THREAD

**Issue by Simon-the-Shark** [boyan01/overlay_support#30]
How about ability to send fixed custom notification?

**Comment by boyan01** [comment]
sure.

> ///
> /// [duration] the overlay display duration , overlay will auto dismiss after [duration]
> /// if null , will be set to [kNotificationDuration]
> /// if zero , will not auto dismiss in the future
> ///
> 

see: https://github.com/boyan01/overlay_support/blob/346b90cf538b730f666c116de15239d7c0d7406f/lib/src/overlay.dart#L26
