### ISSUE TITLE
有类似可以关闭所有overlay的方法吗

### ISSUE THREAD

**Issue by lostcixin** [boyan01/overlay_support#35]
有类似可以关闭所有overlay的方法吗

**Comment by boyan01** [comment]
没有关闭所有overlay的方法。能问一下为什么会有这种需求么？

**Comment by lostcixin** [comment]
> 没有关闭所有overlay的方法。能问一下为什么会有这种需求么？



> 没有关闭所有overlay的方法。能问一下为什么会有这种需求么？

有时候弹框太多了

**Comment by boyan01** [comment]
这种情况的话，我觉得你弹出 overlay 之后，可以用一个 List 将返回的 `OverlaySupportEntry` 保存起来，然后自己清理即可，没必要放到库里面来。
