### ISSUE TITLE
dismiss notification on press

### ISSUE THREAD

**Issue by nicolasvahidzein** [boyan01/overlay_support#36]
hello,

wonderful package and thank you.

Can you tell me please how i can dismiss the notification as soon as i press on it? I'm using the complex notification, not the simple one.

showOverlayNotification

Thanks.

**Comment by boyan01** [comment]
use this statement in you onPress callback.
```
 OverlaySupportEntry.of(context).dismiss();
```
You can see here： https://github.com/boyan01/overlay_support/tree/master/example

**Comment by nicolasvahidzein** [comment]
Thank you so much. Cheers.
