### ISSUE TITLE
NoSuchMethodError: The method 'hide' was called on null.

### ISSUE THREAD

**Issue by huzhiren** [boyan01/overlay_support#4]
Thank you for such a fantastic package.   I spot an exception:

NoSuchMethodError: The method 'hide' was called on null.
Receiver: null
Tried calling: hide()
#0      NotificationEntry.dismiss (package:overlay_support/src/overlay_entry.dart:22)
#1      showOverlay.<anonymous closure>.<anonymous closure> (package:overlay_support/src/overlay.dart:43)
#2      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988)
#3      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:904)

**Comment by boyan01** [comment]
Which version are you using?

**Comment by Goolpe** [comment]
I have the same issue on flutter v 1.5.8

**Comment by boyan01** [comment]
i will try to figure out the cause, but it will be very helpful if you can provide specific code .

**Comment by Goolpe** [comment]
if I use separate funcs:
NotificationEntry entry;
Column(
  mainAxisAlignment: MainAxisAlignment.center,
  children: <Widget>[
    RaisedButton(
      color: Colors.red,
      child: Text('show'),
      onPressed: (){
        entry = showSimpleNotification(context,
          const Text('Load video'),
          elevation: 0,
          autoDismiss: false);
      },
    ),
    RaisedButton(
      color: Colors.green,
      child: Text('dismiss'),
      onPressed: (){
        entry.dismiss();
      },
    )
  ]
)
works fine, but if in one function like:
NotificationEntry entry;
RaisedButton(
  color: Colors.red,
  child: Text('show'),
  onPressed: (){
    entry = showSimpleNotification(context,
      const Text('Load video'),
      elevation: 0,
      autoDismiss: false);
    entry.dismiss();
  },
),
receive error

**Comment by boyan01** [comment]
i think this should be a wrong use case, because we should not dismiss notification immediately when we popup a notification into screen. 

but this also should be a problem,  I only add protect logic for autoDismiss  : https://github.com/boyan01/overlay_support/blob/2aedf6d8a4ada3979391e781989048f3b0500921/lib/src/overlay.dart#L42

thanks for the information, i will fix this in next version.

**Comment by huzhiren** [comment]
Sorry, coming back late.

How I use:

First, because I used another library before, so here is a wrap function:
```
void showToast({@required BuildContext context, String title, @required String message, Duration duration = const Duration(seconds: 3)}) {
    toast(context, message, duration: duration);
}
```

Then use it like:
```
showToast(message: "doing something successfully", duration: Duration(seconds: 2));
Navigator.pop(context, true);
```

So I think the `Navigator.pop(context, true); `  should screw the status of the overlay.

**Comment by boyan01** [comment]
in normally use case, `Navigator.pop` does not affect the status of Overlay, because the `Overlay` is a  application level Widget.

is that you used one of `Overlay`,`WidgetsApp` or `MaterialApp` widget in a single page?

**Comment by huzhiren** [comment]
So that is weird.  I use `MaterialApp` as root widget tree.

**Comment by boyan01** [comment]
maybe i found the cause, i guess you used `ReorderableListView` or  something wrapped a `Overlay` widget.
