### ISSUE TITLE
Overlay is not visible when keyboard is open

### ISSUE THREAD

**Issue by kashlo** [boyan01/overlay_support#44]
When textfield is focused and keyboard is open overlay is not visible when called

**Comment by boyan01** [comment]
Flutter can not render anything above keyboard, so I have no way...
Maybe you can offset the overlay when keyboard been popped. Just like this:
![Screenshot_20200622-004231_Chrome](https://user-images.githubusercontent.com/17426470/85230221-59b25000-b421-11ea-92fb-36fcc263924c.jpg)

**Comment by kashlo** [comment]
I think in this case message should appear on top of the keyboard, as it works in snackbar

**Comment by boyan01** [comment]
Sorry for delay.

Just like https://github.com/boyan01/overlay_support/issues/45#issuecomment-691643498 .

This library was designed to show widget above flutter widget tree. And this library is limited by `FlutterView`, so it can not show anything above `SoftKeyBoard` or other platform view who covered the `FlutterView`.

So I going to close this issue. Thank you.
