### ISSUE TITLE
#51 main.dart not found

### ISSUE THREAD

**Issue by shivanigupta19** [boyan01/overlay_support#51]
main.dart not found

**Comment by boyan01** [comment]
Could you give me more information, so I can reproduce this problem ?

**Comment by shivanigupta19** [comment]
main.dart is not found

**Comment by boyan01** [comment]
我猜你可能想错了。

This is a library, **Not an application**, so it is not necessary to include a `main.dart` file

**Comment by boyan01** [comment]
close due to **No Further Informations**
