### ISSUE TITLE
There is already an OverlaySupport in the Widget tree.

### ISSUE THREAD

**Issue by long1eu** [boyan01/overlay_support#54]
I have a an use-case where I have multiple Material apps and implicitly I need multiple OverlaySupport. How can I achieve this?

**Comment by boyan01** [comment]
For this kind of case, you only need to wrap the outermost MaterialApp Widget.

**Comment by long1eu** [comment]
That doesn't save the problem. I have multiple navigators so using the root one is not an option. What would help is to be able to pass in a navigator instance.

**Comment by boyan01** [comment]
> That doesn't save the problem. 

why? It should be able to solve this problem.

Use the outermost Navigator to ensure normal operation. The reason why this library gets the navigator instance is only because the navigator can provide an overay instance.

**Comment by long1eu** [comment]
As I said I have multiple material app so multiple navigators. If I use it  as you said the notification will be presented on the whole screen using the root navigator. I want to show the notification only over specific navigator.

In this example I will see the notifications from all these three instances on the whole page. I want them to be visible in their container. That means their own navigator.

![Screenshot 2020-10-21 at 17 26 19](https://user-images.githubusercontent.com/9283414/96733860-963b8b80-13c2-11eb-991e-f111e8385039.png)

**Comment by boyan01** [comment]
I got it. (A picture is worth a thousand words

Razvan Lung <notifications@github.com> 于 2020年10月21日周三 22:27写道：

**Comment by boyan01** [comment]
Thanks for advice. ❤️ 

fixed in 
![image](https://user-images.githubusercontent.com/17426470/111071749-945d9a80-8512-11eb-9918-28bf0dca24cd.png)

introduced a new api `OverlaySupport.global()` and `OverlaySupport.local()`. 

example: https://github.com/boyan01/overlay_support/blob/master/example/lib/pages/page_multi_overlay_support.dart

Please fell free to reopen this issue if you have any problem.
