### ISSUE TITLE
Dismiss showOverlayNotification Programmatically

### ISSUE THREAD

**Issue by AhW00** [boyan01/overlay_support#56]
How can I dismiss an OverlayNotification before showing another one?

I tried OverlaySupportEntry.of(context)?.dismiss(); before showing the notification but it doesn't show anything!

I tried to await OverlaySupportEntry.of(context)?.dismissed; but it gives an error, probably because there isn't any notification when calling it.

Is there any way to check if there's a notification showing before I call OverlaySupportEntry.of(context).dismiss(); ?

Thanks

**Comment by boyan01** [comment]
https://github.com/boyan01/overlay_support/blob/35f6467c8330919778b727e8707a050a0ffddc4c/lib/src/notification/overlay_notification.dart#L15-L20

Maybe you can just hold the OverlaySupportEntry instance which returned by `showOverlayNotification` method, then you can dimiss it in any time

**Comment by AhW00** [comment]
Oh I didn't notice that it returns OverlaySupportEntry instance!

Thank you very much, it worked. 👍
