### ISSUE TITLE
getting The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.

### ISSUE THREAD

**Issue by hemanthkb97** [boyan01/overlay_support#64]
**Describe the bug**
Running "flutter pub get" in safehandsfordoc... Launching lib\main.dart on Chrome in debug mode... lib\main.dart /D:/flutter/.pub-cache/hosted/pub.dartlang.org/overlay_support-1.0.5/lib/src/overlay.dart:156:19: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.

'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/framework.dart'). Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'. if (context.ancestorWidgetOfExactType(OverlaySupport) != null) { ^^^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/overlay_support-1.0.5/lib/src/overlay_entry.dart:17:37: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.

'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/framework.dart'). Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'. final animatedOverlay = context.ancestorWidgetOfExactType(_AnimatedOverlay);

                             ^^^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/overlay_support-1.0.5/lib/src/theme.dart:53:20: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.

'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/framework.dart'). Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'. return context.inheritFromWidgetOfExactType(OverlaySupportTheme) as OverlaySupportTheme;

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application. Exited (sigterm)

**To Reproduce**
1) just added in pubyaml
2) returned OverlaySupport
3) used  showSimpleNotification

**Version (please complete the following information):**
 - Flutter Version: Flutter 1.26.0-17.2
 - OS:  WEB
 - OverlaySupport Version : ^1.0.5

**Comment by fengwang** [comment]
Solution possibly here: https://api.flutter.dev/flutter/widgets/BuildContext/ancestorWidgetOfExactType.html

**Comment by boyan01** [comment]
It seems that new flutter beta version has removed the depcreated function such as `inheritFromWidgetOfExactType`.

Does `1.2.0-nullsafety.0` works for your project ?  if it works , maybe I don’t need to release a new version based on the `1.0.5`

**Comment by hemanthkb97** [comment]
> Solution possibly here: https://api.flutter.dev/flutter/widgets/BuildContext/ancestorWidgetOfExactType.html

this worked thank you so much for the quick response @fengwang  :) 

@boyan01  thank you for response and for this amazing package

**Comment by boyan01** [comment]
For dev who did not migrated to nullsafety. please consider use : 1.0.5-hotfix1
```
overlay_support: ^1.0.5-hotfix1
```
