### ISSUE TITLE
Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'

### ISSUE THREAD

**Issue by talatkuyuk** [boyan01/overlay_support#65]
I receive that message:

../../../.pub-cache/hosted/pub.dartlang.org/overlay_support-1.0.5/lib/src/overlay.dart:156:19: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.

**Version (please complete the following information):**
 - Flutter Version: last version
 - OS: [Android]

**Comment by boyan01** [comment]
dupulicate of : https://github.com/boyan01/overlay_support/issues/64

consider use https://github.com/boyan01/overlay_support/issues/64#issuecomment-775274094

**Comment by talatkuyuk** [comment]
I am in beta channel. 
I have used the below version as you suggested but the problem continues. (I am not using null safety yet.)

overlay_support: ^1.0.5-hotfix1

**Comment by zvikarp** [comment]
@talatkuyuk  same. do `overlay_support: 1.0.5-hotfix1` to force the version (without the `^`)
