### ISSUE TITLE
Issue with RestartWidget.

### ISSUE THREAD

**Issue by mrbamboovn** [boyan01/overlay_support#68]
Hi,
I use RestartWidget or PhoenixWidget  with MaterialApp.  I try to implement overlaysupport.global by following your guide and after that my restart function not work anymore.
Env:
- Flutter channel master
- overlay_support: 1.2.1

Please help!

**Comment by boyan01** [comment]
What is RestartWidget/PhoenixWidget ? 

can you give me a library links or demo so I can reproduced  your description.

**Comment by mrbamboovn** [comment]
This is Phoenix Flutter widget that support app to restart

**Comment by boyan01** [comment]
## Solution
  Your can swap `OverlaySupport` to `PhoenixWidget` parent.
  more you can check here: https://github.com/mobiten/flutter_phoenix/issues/15

## Reason

`GlobalOverlaySupport`  creat with a global key `_keyFinder `, so flutter_phoenix has no effect on it.

https://github.com/boyan01/overlay_support/blob/40e31cf04545c42fb5c7d81c7b2f1fad0e297746/lib/src/overlay_state_finder.dart#L81

**Comment by mrbamboovn** [comment]
It's worked.
Thanks in advantage !
