### ISSUE TITLE
Prevent simple notification from being displayed on specific pages

### ISSUE THREAD

**Issue by zsgithublib** [boyan01/overlay_support#69]
I am using the simple notification widget to present push notifications while the app is open. naturally, I do not want to present simple notifications notifying the user that they have a new chat message if the current active screen is displaying that chat message. 

Because the simple notification function is a global function housed in the main.dart file outside of the material app widget, I have no access to context. How do I determine the current page before firing the simple notification?

**Comment by boyan01** [comment]
maybe you can use a global/static variable to store which chat conversation is  active.
