### ISSUE TITLE
Overlay Support Plugin not working in InitState Method

### ISSUE THREAD

**Issue by Mohanraj153** [boyan01/overlay_support#71]
**Describe the bug**
When I tried to implement your plugin in initstate or start build state then occur error like VisitChildElements() called during build.

**Expected behavior**
I need show Notification on start the app or screen

**Screenshots**
Click to See the Error :
https://ibb.co/VptmtjM

**Version (please complete the following information):**
 - Flutter Version: [e.g. v2.2.3]
 - OS: Android
 - OverlaySupport Version : 1.2.1

**Comment by boyan01** [comment]
Can you provide a mini reproducible code snippet ?

**Comment by Mohanraj153** [comment]
void main() {
  debugDefaultTargetPlatformOverride = TargetPlatform.android;
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return OverlaySupport.global(
      child: MaterialApp(
          title: 'Flutter Demo',
          debugShowCheckedModeBanner: false,
          theme: ThemeData.dark().copyWith(primaryColor: Colors.blue),
          home: Home()),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    showSimpleNotification(
                Text("this is a message from simple notification"),
                background: Colors.green,
                trailing: Icon(Icons.clear)
              );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text("Network Aware App"),
      ),
      body: Center(child: Text("Welcome"),),
    );
  }
}

**Comment by boyan01** [comment]
I don’t think it can be compatible with this case from the library.

But there is a solution: you can delay to show this notification in your initState method.

```dart
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    scheduleMicrotask(() {
      showSimpleNotification(Text("this is a message from simple notification"),
          background: Colors.green, trailing: Icon(Icons.clear));
    });
   ...
```
