### ISSUE TITLE
Add valid copyright information

### ISSUE THREAD

**Issue by b3arco** [boyan01/overlay_support#75]
Currently, in the [LICENSE file](https://github.com/boyan01/overlay_support/blob/master/LICENSE), the copyright information is not correct. It literally reads (in line 189):

```diff
Copyright [yyyy] [name of copyright owner]
```

Could you please add a valid year and name?

**Comment by boyan01** [comment]
Thanks for reminder.  fix in https://github.com/boyan01/overlay_support/commit/9db38b2ea2fa8fa827b7aa197111fa4ed6e52927
