### ISSUE TITLE
WidgetsBinding.instance now is not nullable

### ISSUE THREAD

**Issue by DJafari** [boyan01/overlay_support#76]
in latest version of flutter `WidgetsBinding.instance` changed type from nullable to non nullable

we get this warning :

```
Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
```

**Comment by maximletushov** [comment]
Dear developers of package please change this code
`WidgetsBinding.instance?.scheduleFrameCallback((_) => animateRemove());`
to this
`WidgetsBinding.instance.scheduleFrameCallback((_) => animateRemove());`
Thanks!

**Comment by boyan01** [comment]
is this break change already in beta channel? I'll publish a new version to fix this if so.

( flutter has changed this before, but reverted. So it is needed to wait this break change more "stable".

**Comment by maximletushov** [comment]
@boyan01 yes, this already in beta channel. Also I checked stable channel and there is no problem. So this is a break change only in beta. I think we can wait more since compiler treats this as warning. Thank you.

**Comment by DJafari** [comment]
@boyan01 i think you must release as major upgrade or release a beta version

2.0.0 or 2.0.0-preview

**Comment by boyan01** [comment]
closed via  https://pub.dev/packages/overlay_support/versions/2.0.0-beta.0

**Comment by rd-martin-jaeger** [comment]
Hi still get the same error:

`../../sdk/.pub-cache/hosted/pub.dartlang.org/overlay_support-2.0.0-beta.0/lib/src/overlay_entry.dart:102:9: Warning: The class 'WidgetsBinding' cannot be null.
Try replacing '?.' with '.'
        WidgetsBinding?.instance.scheduleFrameCallback((_) => animateRemove());
        ^^^^^^^^^^^^^^
../../sdk/.pub-cache/hosted/pub.dartlang.org/overlay_support-2.0.0-beta.0/lib/src/overlay_entry.dart:102:34: Error: Method 'scheduleFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../sdk/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
        WidgetsBinding?.instance.scheduleFrameCallback((_) => animateRemove());`

**Comment by DJafari** [comment]
@rd-martin-jaeger if you aren't on flutter master channel and latest version you must avoid using of version 2.0.0-betta of this library

**Comment by rd-martin-jaeger** [comment]
Hi, thanks for the fast answer. 

Due to the company policy i have to use flutters stable channel, so master isn't an option for me. 
As you can see in my snipped, i already use the 2.0.0-beta.0 and still got the error.

Here the missing flutter doctor output:
```
➜  example git:(master) ✗ flutter doctor -v                
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-DE)
    • Flutter version 2.10.5 at /Users/oxx/dev/flutter/sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/oxx/dev/android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

```

**Comment by DJafari** [comment]
@rd-martin-jaeger hi, you're welcome

so you must using version : `1.2.1` of this library

```yaml
overlay_support: ^1.2.1
```
