### ISSUE TITLE
Flutter 3 Support

### ISSUE THREAD

**Issue by erabti** [boyan01/overlay_support#79]
Just update your flutter to latest 3.0.0 release.

```
Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../fvm/versions/stable/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance?.scheduleFrameCallback((_) => animateRemove());
```

**Comment by boyan01** [comment]
relate to https://github.com/boyan01/overlay_support/issues/76

You can use [2.0.0-beta.0](https://pub.dev/packages/overlay_support/versions/2.0.0-beta.0)

I'll publish a stable 2.0.0 version in few days.

**Comment by boyan01** [comment]
`overlay_support: ^2.0.0` published
