### ISSUE TITLE
error: The class 'WidgetsBinding' cannot be null

### ISSUE THREAD

**Issue by ironda2020** [boyan01/overlay_support#80]
**Describe the bug**
![image](https://user-images.githubusercontent.com/76248749/168493778-d4484c35-17d0-4e2b-8bf2-4c260c0995c9.png)

**To Reproduce**
- Add OverlaySupport to flutter project (v2.10.5)
- Execute "flutter run"

![image](https://user-images.githubusercontent.com/76248749/168493747-61767a06-339e-4840-8805-5a4ea8575226.png)

**Expected behavior**
 "flutter run" should work correctly

**Version (please complete the following information):**
 - Flutter Version: [v2.10.5]
 - OS: [Android]
 - OverlaySupport Version : [v2.0.0]

**Proposed solution**
To fix this problem, you need to add **!** to file **overlay_entry.dart** on line **102** (as in the screen below)
![image](https://user-images.githubusercontent.com/76248749/168493695-69bf2147-d5d6-431c-ba53-325344485c85.png)

**Comment by boyan01** [comment]
`overlay_support: 2.0.0` only compat with flutter 3.0

please check https://github.com/boyan01/overlay_support/issues/76#issuecomment-1119642865

**Comment by msnmuhsinpt** [comment]
use version 1.0.0

**Comment by boyan01** [comment]
https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings
