### ISSUE TITLE
Dismissed or closed notification

### ISSUE THREAD

**Issue by doriansabo** [boyan01/overlay_support#82]
Is there a way to know when the notification is dismissed or closed?

**Comment by boyan01** [comment]
Yes. the `showOverlayNotification` function returns a object `OverlaySupportEntry`.

https://github.com/boyan01/overlay_support/blob/cf782231bb51e5f5cc28d32622325b8661820286/lib/src/notification/overlay_notification.dart#L13

you can use `OverlaySupportEntry.dismissed`  to know the time when dimissed.

https://github.com/boyan01/overlay_support/blob/cf782231bb51e5f5cc28d32622325b8661820286/lib/src/overlay_entry.dart#L44


for example:

```dart
  OverlaySupportEntry entry = ...;
  await entry.dissmissed;
  debugPrint('notifiication dismissed');

```
