### ISSUE TITLE
Make overlays and toasts clickthrough

### ISSUE THREAD

**Issue by blue1stone** [boyan01/overlay_support#85]
Thanks a lot for making this fantastic package!

It would be great if there were a way to make the overlays and toasts optionally clickthrough.
I use this package to display an info notification, but it currently blocks other elements behind it from being clicked. This is suboptimal as it breaks the flow of the app. Would this be possible?

**Comment by boyan01** [comment]
> It would be great if there were a way to make the overlays and toasts optionally clickthrough.

Sorry, I can not get the picture in my mind for `optionally clickthrough`.  Can you give me more details of this?


>  it currently blocks other elements behind it from being clicked. 

Because in my understanding, the front elements in the UI should intercept click events. This is also the default behavior of flutter.

**Comment by blue1stone** [comment]
Sorry for being unclear.

I mean that e.g. when launching an overlay, it would be great if you could provide an option, a simple boolean for example, to make the overlay blocking or non-blocking.
Although the default behavior in Flutter is to be blocking, I think it would be useful to get this option. E.g. native toasts in Android are clickthrough too (to my knowledge at least).

**Comment by boyan01** [comment]
You can wrap your custom overlay with `IgnorePointer` widget, then your custom overlay wouldn't  interupt any touch event anymore. 

The package provider toast has been warpped `IgnorePointer`   in 76b0cee16c1019f2491bbe415127f76f884b5d5c

**Comment by blue1stone** [comment]
Awesome! Exactly what I was looking for, thanks a lot for the help!
