### ISSUE TITLE
Dismiss direction for showOverlayNotification

### ISSUE THREAD

**Issue by nicolasvahidzein** [boyan01/overlay_support#90]
Hello,

Thank you for your wonderful package. Is it possible to setup a direction for the dismissal of this type of notification like we can with the ShowSimpleNotification?

I know i can setup a dismissal if i just press on it but that is not what i want.

Thanks.

**Comment by boyan01** [comment]
you can wrap your custom notification with `SlideDismissible` widget

`showSimpleNotification` also do the same thing: https://github.com/boyan01/overlay_support/blob/master/lib/src/notification/overlay_notification.dart#LL113-L115
